# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
services:
  commons-lang-test:
    build:
      context: .
      dockerfile: Dockerfile
    image: commons-lang3:latest
    container_name: commons-lang-test
    volumes:
      - ./target:/commons-lang/target
    profiles:
      - test
    command: mvn test

  commons-lang-coverage:
    build:
      context: .
      dockerfile: Dockerfile
    image: commons-lang3:latest
    container_name: commons-lang-coverage
    volumes:
      - ./target:/commons-lang/target
    profiles:
      - coverage
    command: mvn clean verify site

  commons-lang-mutation:
    build:
      context: .
      dockerfile: Dockerfile
    image: commons-lang3:latest
    container_name: commons-lang-mutation
    volumes:
      - ./target:/commons-lang/target
    profiles:
      - mutation
    command: mvn org.pitest:pitest-maven:mutationCoverage

  commons-lang-benchmark:
    build:
      context: .
      dockerfile: Dockerfile
    image: commons-lang3:latest
    container_name: commons-lang-benchmark
    volumes:
      - ./target:/commons-lang/target
    profiles:
      - benchmark
    command: mvn test