name: SonarCloud Analysis

on:
  push:
    branches:
      - master
      - jml-specifications
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B clean verify site \
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar